server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:nerdstrom
    generate-unique-name: false

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
      generate-ddl: true
      ddl-auto: none


